language: node_js
node_js:
  - 6
env:
- NODE_ENV=TEST
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_success:
- test $TRAVIS_TEST_RESULT = 0 \# check build success 
  && npm run-script jshint
  && npm run-script coverage
  && bash travis.sh
