language: node_js
node_js:
  - 6
env:
- MY_VAR=EverythignIsAwesome
- NODE_ENV=TEST
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_script:
- npm run-script jshint
- npm run-script coverage
