language: node_js
node_js:
  - 6
env:
- NODE_ENV=TEST
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_success:
- npm run-script jshint
export TRAVIS_TEST_RESULT=$?
echo "Done. Build script exited with $TRAVIS_TEST_RESULT" 
- npm run-script coverage
export TRAVIS_TEST_RESULT=$?
echo "Done. Build script exited with $TRAVIS_TEST_RESULT" 
- bash travis.sh
export TRAVIS_TEST_RESULT=$?
echo "Done. Build script exited with $TRAVIS_TEST_RESULT" 
