language: node_js
node_js:
  - 6
env:
- NODE_ENV=TEST
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_success:
- echo "test_result: $TRAVIS_TEST_RESULT"
- test $TRAVIS_TEST_RESULT = true && npm run-script jshint
- npm run-script coverage
- bash travis.sh
