language: node_js
node_js:
  - 6

# declare your environment variables
env:
  # global will stay the same across all matrix possibilities (will not create additional combinations to run)
  global:
    - SECRET_TOKEN=k399dkkgklsk
  # matrix variables will create a new build for each specified variable
  matrix:
    - DB=production

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  

after_success:
   - if [[ "$TRAVIS_TEST_RESULT" == "0" ]]; then npm run-script jshint    ; fi
  #- if [[ "$TRAVIS_TEST_RESULT" == "0" ]]; then npm run-script coverage    ; fi

after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

- bash ./travis.sh 


