language: node_js
node_js:
  - 6

# declare your environment variables
env:
  # global will stay the same across all matrix possibilities (will not create additional combinations to run)
  global:
    - SECRET_TOKEN=k399dkkgklsk
  # matrix variables will create a new build for each specified variable
  matrix:
    - DB=production

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success:
- test $TRAVIS_TEST_RESULT = 0 \ 
  && npm run-script jshint 
  
- test $TRAVIS_TEST_RESULT = 0 \   
  && npm run-script coverage 
  
- bash travis.sh
