language: node_js
node_js:
- 6

#before_script:  
#- export DISPLAY=:99.0
#- sh -e /etc/init.d/xvfb start

after_script:
- echo $env_test

notifications:
  email:
    recipients:
      - h.eissler@de.ibm.com     
    on_success: always
    on_failure: always
